site_name: Automotive Grade Linux Documentation Site
site_url: http://agl-docs.readthedocs.io/
site_author: Shankho Boron Ghosh
theme_dir: hacks/
theme: 
  name: rtd-dropdown
  include_sidebar: false
  

plugins:
  - search:
      separator: '[\s\-\_]+'


